### ISSUE TITLE
Support for TNG

### ISSUE THREAD

**Issue by raphink** [jeffg2k/SmartCopy#34]
I'm thinking of adding support for TNG websites. There is one with lots of data that interests me (e.g. http://www.farhi.org/genealogy/getperson.php?personID=I23140&tree=Farhi).

So that would probably be a generic collection with multiple URLs for all TNG websites we can list. Would you be interested?

**Comment by jeffg2k** [comment]
Yeah, that would be nice.  I've seen this site format before.  So correct me if I'm wrong.. these are not managed by a single site, corporation, or domain.  They are stood up by individuals using various domain names, likely based off some desktop software html export.  Is that correct?

I see a few options with that type of site. 
    1) Keep track of various domains and add a register for it
    2) Wildcard the manifest to support any domain, detect TNG url structure excluding domain, such as detecting "/genealogy/getperson.php"
    3) Wildcard the manifest to support any domain, allow for code based detection of TNG.  Have it look at the code to see if the site is supported.

My preference would probably be #2 to give the broadest support for the parser.  The users would likely get a warning that the permissions changed and get a warning that this extension can read any site, but it would be doing it for a reason and I can explain that in the discussion.

Couple things to look at:
    1) I don't see a change in the url when setting the language to english.  We'll need a way to force a language unless the fields are easily defined in the code via class or id.
    2) I had another thing, but now I can't recall it. lol

**Comment by raphink** [comment]
Actually, I think I'd father 3) with a method for the collection that would return true if the site is supported. We could easily port all the other collections this way so they use the URL as the criteria, and collections in general could use other criteriae.

**Comment by jeffg2k** [comment]
You could also combine 2 and 3, where it only does code based detection if the url looks like on the parser supports.

**Comment by raphink** [comment]
Yes, that's true, although 3 being a more generic option would cover all needs with only one method.

**Comment by jeffg2k** [comment]
Maybe - if the page code is dependent on being on the correct page or in english, you may need to reload it.  For example, if you were looking for code on getperson.php, but the user was on familychart.php - option 3 may fail unless you first check the url, reformat it and reload the source for getperson.php.

**Comment by jeffg2k** [comment]
But hopefully there would be a generic part that would apply to the entire site that you could key off of, then you could better look at the url.

**Comment by jeffg2k** [comment]
Certainly, feel free to implement it how you think best.  We can tweak as we go if needed.

**Comment by raphink** [comment]
In the case of TNG, there is a comment in the head section of every page, so we can probably parse that:

```html
<!-- The Next Generation of Genealogy Sitebuilding, v.11.0.2 (16 Sep 2016), Written by Darrin Lythgoe, 2001-2017 -->
```

**Comment by raphink** [comment]
I wish all these website had a json version, with just `format=json` or appending `.json` to URLs :smile:

**Comment by jeffg2k** [comment]
That would be great.  FamilySearch does a pretty good job.
Hey.. you mind if I add your name to the "Special Thanks" section?  I'd like to recognize your programming contributions in the app info page.

**Comment by raphink** [comment]
No problem, go ahead, thank you.

**Comment by jeffg2k** [comment]
I'm hoping the activeTab method will address the permissions problem with this.  See issue #44

**Comment by raphink** [comment]
I think I can close this, right?

**Comment by jeffg2k** [comment]
Almost done - there are a few more TODO's.  Need to capture the marriage data, identify half-siblings, and define the other parent for a child when multiple spouses exist.

**Comment by raphink** [comment]
OK :smile:

**Comment by jeffg2k** [comment]
Requires more testing across different sites - tried on two other TNG sites and it failed.
http://lythgoes.net/genealogy/usersites.php
