### ISSUE TITLE
See if activeTab can replace tabs permission

### ISSUE THREAD

**Issue by jeffg2k** [jeffg2k/SmartCopy#44]
Can activeTab replace tabs permission in the manifest file in order to remove warning and improve security / privacy for SmartCopy?
https://developer.chrome.com/extensions/permission_warnings
https://developer.chrome.com/extensions/management#method-getPermissionWarningsByManifest

**Comment by jeffg2k** [comment]
I'm not sure that this allows for xhttp to urls other than the activeTab url.  That would be fine if we were to define our common domains, but if we need to reload the url to be on the correct page, it may not work.

**Comment by jeffg2k** [comment]
This does appear to work if the domain is the same, but not if the host name is different.

So if I'm on www.findagrave.com then I can query www.findagrave.com, but if I'm on forums.findagrave.com or findagrave.com, I can't change the hostname to www.findagrave.com.

**Comment by jeffg2k** [comment]
Started with activeTab changes - let's see if this will work: https://github.com/jeffg2k/SmartCopy/commit/f4017297f74c0560437a0e8965a8993b4e14fab0

**Comment by raphink** [comment]
Pretty cool. Maybe with redirections ?
