### ISSUE TITLE
FR: tree matches

### ISSUE THREAD

**Issue by raphink** [jeffg2k/SmartCopy#47]
As you parse informations with SmartCopy and create new profiles in the tree, it gets increasingly likely that you're creating duplicates. Going on Geni for each person to check if they're duplicates is tedious, so it would be very useful if the popup had a tree matches button with up-to-date information from Geni.

It doesn't look like the API provides this though, so I don't know how that would be technically feasible.

**Comment by jeffg2k** [comment]
Right, Geni doesn't have an API for matches.  I can ask Geni though - maybe they would add it.

**Comment by raphink** [comment]
That would be great. What would also be great would be more fields for evens, such as participants. This would allow to tag people in events (birth, marriage, death) that are imported.

**Comment by jeffg2k** [comment]
Geni has granted the request and added an API field for matches. :)

https://stage.geni.com/api/profile-1693836?fields=name,match_counts

**Comment by raphink** [comment]
Oh very cool, let's code that then !

**Comment by jeffg2k** [comment]
Completed Tree Match notice with https://github.com/jeffg2k/SmartCopy/commit/59046d8ccfe129ff2c0f78bad246235a3b7ff38c & https://github.com/jeffg2k/SmartCopy/commit/5b6b3ed1554365618e372bf63bf221c79703328c

**Comment by raphink** [comment]
Very nice
