### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by raphink** [jeffg2k/SmartCopy#52]
Lots of things have changed since the last release was cut. It would be great to make a new one, especially to announce support for geneanet, TNG and basic member changes...

Also, afaic, geneanet is fully functional for me, except for two things:

* the current profile tends to receive info from whichever person was last parsed it seems (#53)
* Empty marriage date results in wrong date as whichever date comes next (usually the birth date of the spouse) gets parsed instead (#54)

**Comment by jeffg2k** [comment]
I plan to increment to 3.0 for the release.
