### ISSUE TITLE
Geneanet: current profile gets wrong info

### ISSUE THREAD

**Issue by raphink** [jeffg2k/SmartCopy#53]
the current profile tends to receive info from whichever person was last parsed it seems

**Comment by jeffg2k** [comment]
I haven't been able to reproduce this.  Could you provide an example or describe it a bit more?  I did fix something like this about 10 days ago in Geneanet - not sure if it's the same problem you're describing though. https://github.com/jeffg2k/SmartCopy/commit/c799d4d2ee08e8ed9b9ee6e154c29b1806d31872

**Comment by raphink** [comment]
Ah, I'll have to check then.
