### ISSUE TITLE
Geneanet: wrong marriage date when empty

### ISSUE THREAD

**Issue by raphink** [jeffg2k/SmartCopy#54]
Empty marriage date results in wrong date as whichever date comes next (usually the birth date of the spouse) gets parsed instead

**Comment by jeffg2k** [comment]
You have a link to one?  Seems all the trees I'm testing against have a date.

**Comment by jeffg2k** [comment]
Disregard - found one

**Comment by jeffg2k** [comment]
https://github.com/jeffg2k/SmartCopy/commit/5d3ddd62ebf3c0f861a2bed1c6571e9da69b0f4c

**Comment by raphink** [comment]
Great!
