### ISSUE TITLE
Geneanet: support French locale

### ISSUE THREAD

**Issue by raphink** [jeffg2k/SmartCopy#57]
I'm quite happy with using Geneanet in English and it was I think the easiest option to get it supported by SmartCopy, but whenever this new feature is released I would like to announce it to the French Geni user groups, and I'm afraid lots of them will struggle with having to use English, so I'm wondering if it would be wise to add French localization support to the collection. What do you think @jeffg2k ?

**Comment by jeffg2k** [comment]
They don't have to view it in English.  They can view the site in French.  I just direct all the XHR queries to the English version of the site for parsing.  So while they're seeing French, I'm actually querying the English version for the data.  Are you thinking something different?

**Comment by jeffg2k** [comment]
I'm looking for a Geneanet profile that has a profile picture if you find one.  I don't think we're parsing the picture yet.

**Comment by raphink** [comment]
Ah great, I hadn't seen that!

As for pictures, they're usually close to tree owners. I'll try to find one.

**Comment by raphink** [comment]
Just found a profile with a pic http://gw.geneanet.org/fdh1?lang=en&pz=daniel+j.s.m.&nz=peeters&ocz=0&p=stephanie&n=delmot but I don't have any corresponding profile on Geni.

**Comment by jeffg2k** [comment]
During testing, I just select something random from the history.  Mainly, I'm looking at data population on the left column.  I only need an appropriate Geni profile if I'm clicking submit and have the blocksend feature off.
