### ISSUE TITLE
what is #compountlastonoffswitch ?

### ISSUE THREAD

**Issue by Jens-dojo** [jeffg2k/SmartCopy#61]
Hi,

great library and I would like to use the NameParse function.

But I am unsure how to replace the following for a stand-alone use ?

    if ($('#compountlastonoffswitch').prop('checked') && this.is_compound_lastName(nameParts[j])) {
    			                        lastName += " " + nameParts[j].toLowerCase();
    			                    } else {
    			                        lastName += " " + this.fix_case(nameParts[j]);
    			                    }

**Comment by jeffg2k** [comment]
The $('#compountlastonoffswitch').prop('checked') is an option I give the user to force the compound last name to lowercase as some countries do.  For example, "van Nostrand" vs "Van Nostrand".  You could either just remove it:
```
lastName += " " + this.fix_case(nameParts[j]);
```
or give the user the option in the function similar to detectMiddleName.

**Comment by Jens-dojo** [comment]
Thank you for your quick hel.
Last question: what is 

    !$('#adjustnameonoffswitch').prop('checked')

**Comment by jeffg2k** [comment]
This is another option that auto-adjusts the name for Mixed Case.

**Comment by Jens-dojo** [comment]
Excellent work ! Thank you !!
