### ISSUE TITLE
Names in other languages ignored in checks

### ISSUE THREAD

**Issue by mustju** [jeffg2k/SmartCopy#64]
Here is a sample profile where names in English language tab have been written correctly  with uppercase initial letter followed by lowercase, but other language tabs contain names in all uppercase:

https://www.geni.com/people/TESTI-PROFIILI/6000000063926796830

SmartCopy does not detect these incorrectly written names. Other name checks won't work either for the other language names.

**Comment by mustju** [comment]
Addressed in #65

**Comment by jeffg2k** [comment]
Thanks - will take a look soon
