### ISSUE TITLE
Naming update

### ISSUE THREAD

**Issue by Trebia** [jeffg2k/SmartCopy#66]
Once a profile exists, is not possible to update the namings, at least the option is not available. If surname or name are updated is not possible to use SmartCopy to update the name.

For example, in attached picture I would have expected to have an slot for updating the name in the location I am marking
![inesgarciafernandezsmartcopymissingname](https://user-images.githubusercontent.com/9620396/28981066-646c67f6-7950-11e7-9f5d-391fab1e0de6.png)

**Comment by jeffg2k** [comment]
Click the little eye icon.

**Comment by jeffg2k** [comment]
Alternatively, there is an option in the settings: turn off "Simplify form by hiding unused fields"

**Comment by Trebia** [comment]
Great! It works! However I did not find this "hint" in the user manual (I understood is this webpage: https://www.geni.com/projects/SmartCopy/18783)

Shall I update that webpage with this information or will make more sense to create a wiki in github?

I would like to contribute as far as I can.

**Comment by jeffg2k** [comment]
Yes, feel free to update the SmartCopy project. :)

**Comment by Trebia** [comment]
Do you know how can I know the address of an image that I have just uploaded?: https://www.geni.com/photo/view/6000000041202209122?album_type=project&end=&photo_id=6000000064349175851&project_id=18783&start=&tagged_profiles=
Just starting to do it :)

**Comment by jeffg2k** [comment]
Click the "Full Size" button.  Then remove the amazon prefix so it just starts with {{//photos.geni.com/...}} in the wiki.

**Comment by jeffg2k** [comment]
The current text on the page says this with regard that feature.  So might be good to put the image there and enhance as needed.

"The “Simplify Form” function has moved to a small “eye” icon within each person’s details so that it can easily be toggled between showing all of a person’s detail fields (blue eye), or hiding most empty fields (the ‘simplified fields’ - grey eye)."

**Comment by Trebia** [comment]
f**k, that was easy!

I followed your suggestions, thanks!
