### ISSUE TITLE
Update of a date not transferred properly.

### ISSUE THREAD

**Issue by Trebia** [jeffg2k/SmartCopy#67]
I have a date in familysearch which is different from the one in Geni. When I try to update the date using SmartCopy the date gets not updated and actually gets a different date in 2020.

The profile with the issue is:

- Geni: https://www.geni.com/people/Inez/6000000064324971857
- FamiliySearch: https://familysearch.org/tree/person/MPWT-9FS/details

The error happens with the date of birth

Notice that it might be the case that the error is a localization error, as I have not found this with other dates.

Se the attached picture for further info:

![inesgarciafernandezsmartcopyupdatedateissue](https://user-images.githubusercontent.com/9620396/28981210-2c4a28e4-7951-11e7-95a7-0635f23fd196.png)

**Comment by jeffg2k** [comment]
Abril is not a month

**Comment by jeffg2k** [comment]
I'll investigate why it's getting that though as the page itself says Apr.

**Comment by Trebia** [comment]
That's what I mentioned, Abril is a month... in Spanish!

**Comment by mustju** [comment]
Some need for internationationalization there also?

**Comment by jeffg2k** [comment]
SmartCopy does not do Spanish dates.

**Comment by jeffg2k** [comment]
I think I can fix this though, at least for FamilySearch.  There is a "localizedText" version and I specify the localization to EN.

**Comment by Trebia** [comment]
Is not possible to get the info of the month by number?

**Comment by jeffg2k** [comment]
This is the actual return I'm working with for that profile: https://familysearch.org/tree-data/person/MPWT-9FS/all?locale=en

**Comment by mustju** [comment]
That link works for you:
> Missing Session Id
> 
> Sorry, the call you attempted requires a session id and I couldn't find one.

**Comment by jeffg2k** [comment]
This is fixed in version 4.2.8, which should be available to Chrome browsers within the next hour.

**Comment by Trebia** [comment]
Tested and works!
