### ISSUE TITLE
Surname wrongly identified

### ISSUE THREAD

**Issue by Trebia** [jeffg2k/SmartCopy#71]
The Spanish and Portuguese name coventions imply that the first surname of the mather and the father are inherited by the children. So, usually 2 words are included in the surnames.

When using SmartCopy (you can see this FamilySearch profile: https://familysearch.org/tree/person/MPWT-9FS/details) it recognizes 2 words and assignes the first word as middle name (it would make sense if would have taken the second word in the name!) and the second word is used as birth surname.

Actually this is another difference in naming conventions, the identity/surname after a marriage remains the same, women or men do not change their surnames after marriage, so birth surname is only applicable to people actually changing their names.

![smartcopysurnamefamiliysearch](https://user-images.githubusercontent.com/9620396/28982643-dad2d1fe-7956-11e7-915e-58fa70b2f6db.png)
![smartcopysurnames](https://user-images.githubusercontent.com/9620396/28982644-dad8517e-7956-11e7-9352-772a3d8b24d2.png)

**Comment by jeffg2k** [comment]
I'll take a look.  FamilySearch is one of the few that actually break it down easily and I haven't set something up to override the default single string.
In the meantime, there are a few options in the configuration for Naming that may help with different formatting.

**Comment by Trebia** [comment]
I made some testing and is not fixing the proble, in anycase is always sending the information to suffix.

Thanks!
