### ISSUE TITLE
Checking of wrong input

### ISSUE THREAD

**Issue by Thimxx** [jeffg2k/SmartCopy#75]
I made a mistake and I introduced a Geni ID profile incomplete. In this case I introduced all integers but one

In this case:

- I should have introduced: 6000000047461321935
- I introduced                    : 600000004746132193

So it looks it is missing an input checking, in this case checking that the length of the profile id is 19

**Comment by jeffg2k** [comment]
Profile ids come in various lengths - so there is no easy check

**Comment by Thimxx** [comment]
a timeout?

**Comment by jeffg2k** [comment]
Yes, I can look for the Geni returning the error code "Not Found".  I'll include this in the next version.
