### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by mustju** [jeffg2k/SmartCopy#76]
Fetch localized strings from JSON-file with chrome.i18n.getMessage().

**Comment by mustju** [comment]
I have started to convert consistency check warnings in content.js to use chrome.i18n.getMessage() adding at the same time Finnish translations. I would like to provide changes in incremental pull requests over a (potentially longish) time period. There is going to be a lot of changes and it is easier to spot breakages this way.

**Comment by jeffg2k** [comment]
Cool - does chrome.i18n.getMessage work with Firefox and Opera?  I expect it does but wasn't sure if you've verified yet.

**Comment by mustju** [comment]
Yes, it does work also in Firefox and Opera despite the misleading package name. I rechecked this again just now to be absolutely sure. Non-Finnish users should not  notice the change at all as the default locale is English. I am fairly sure that Finnish users do not mind the incompleteness of translations. The used locale is the same as the browser is using, Geni could be using different language, but that would be kind of weird configuration.

**Comment by mustju** [comment]
About that "Non-Finnish users should not notice the change " - Unfortunately the transformation from original texts to localized ones is manual labor and it its easy to make mistakes there. I would expect a few occur if/when I go through all texts.

**Comment by jeffg2k** [comment]
Do you know what happens if I define a string using the localization and have it in the en json file, but not in another language?  Does it default back to the english if the string is missing in another language.  I'm hoping it won't break anything in the other languages if I start adding more strings to the file, but don't yet have a translation for them in the various languages we might end up with.  Hate to have to do them all together at once.. though I guess I could try using Google Translate.

**Comment by mustju** [comment]
It defaults back to English (as specified in manifest.json) if the translation for a phrase is missing for current locale. So you can safely convert all the English language texts to use chrome.i18n.getMessage (or parts of them), while having only part or none of them translated to another language in messages.json. I have tested this with Swedish for which there is no translations present - it defaults to English. I also made a typo on purpose to one key in Finnish translations - this defaulted then back to English as it should.

**Comment by mustju** [comment]
If you later on find a need to change a localized English text in messages.json, it is probably easiest to change the used key in that file and in code. Existing translations will then default to English instead of showing the obsolete translation. Alternatively delete obsolete translations or modify their keys.

**Comment by mustju** [comment]
I am now continuing localization - further pull request(s) to be expected soon...

**Comment by DanCornett** [comment]
The Chrome release 4.3.3 has a problem with the /es/ locale file ... it has to be UTF-8 compatible.

**Comment by jeffg2k** [comment]
I've pushed a fix.

**Comment by jeffg2k** [comment]
I think this can be closed now - @mustju added the necessary components and now it's just a matter of adding additional languages, which is something other devs will need to do.
