### ISSUE TITLE
Fixing capital letters in "nexus" words

### ISSUE THREAD

**Issue by Thimxx** [jeffg2k/SmartCopy#81]
In spanish name customs there are several words used as "nexus" inside surnames.

For example "de la Villa" will be a surname that literally means "from the City". What I am calling nexus are "de" and "la" which are supporting the surname and, in this case, refer to location.

In this case, the nexus are always written in lowercase. I am able to identify 4 nexus: la, del, de, y.

In the current version of SmartCopy when selecting "fix case", the "nexus" are converted into capital letters, when, according to standard naming customs, they shall be in small.

I can give you the example of 2 MP using "de" as nexus and their reference in Wikipedia:

https://www.geni.com/people/Juan-Ponce-de-Le%C3%B3n-I-gobernador-de-Puerto-Rico/6000000002229981181?through=6000000003493176118
https://es.wikipedia.org/wiki/Juan_Ponce_de_Le%C3%B3n

And
https://es.wikipedia.org/wiki/Vasco_N%C3%BA%C3%B1ez_de_Balboa
https://www.geni.com/people/Vasco-Nunez-de-Balboa/6000000035311920266?through=6000000035313135945

So essentially, when fixing upper/lower case what I am proposing is that when nexus are identified they shall be kept their first letter in lowercase

Similarly, you will find the same situation in other languages:

de in french:
https://en.wikipedia.org/wiki/Henri_de_Toulouse-Lautrec
von in german:
https://en.wikipedia.org/wiki/Karl_von_Fischer
van in dutch
https://en.wikipedia.org/wiki/Anthony_van_Dyck

**Comment by jeffg2k** [comment]
If I recall correctly, there should already be an option for that.

**Comment by jeffg2k** [comment]
It should be called "Force compound lastname to lowercase"

**Comment by Thimxx** [comment]
Did not notice that one, but after some testing is it not working.
I testing on these profiles:

"y" particle: https://www.geni.com/people/Joseph-Ruiz-Y-Zarzosa/6000000029340111707
"de" particle: https://www.geni.com/people/Phelipa-Losada-De-Arias/6000000029197829340

**Comment by jeffg2k** [comment]
Ah, so it's in the middle of the last name.  I was thinking like "Von Miller" would be "von Miller".  I was also thinking about the copying, not the consistency check.  I'll take a look.

**Comment by Thimxx** [comment]
Ok... I did not notice in the first shot! All the examples I mentioned I are in the middle of the last name.

So... Spanish namings customs (also south American and protuguese) are different from English one ("El Jefe" should now!!! :) ) essentially a person inherits 2 last names, one from the father and another from the mother. In the past it was always first the father last name and second the mother last name, now the law (in Spain) forces a decision on which one is first.

So 
(fake names)
"Francisco Núñez" and "Felisa de Balboa" will have a son called "Alberto Núñez de Balboa"

So it is not the middle of the last name, is the second last name.

You can have the same situation with the names for example: "María de la Concepción"

**Comment by jeffg2k** [comment]
Pushed out an updated version that should help - the option "Force compound lastname to lowercase" should be turned on for it to work.

**Comment by jeffg2k** [comment]
Note though that a fix case will only trigger if the name value is in all uppercase or all lowercase.  I ignore a mixed case name, even if improperly formatted, and have no intention on testing against mixed case and offering changes.  This fix just allows the situation where a name value that is in all uppercase or all lowercase - the fix will not uppercase the those compound values, such as "de", "la", "y" - it will force them lowercase.
